### PR TITLE
Refactor: ts migration of logout folder

### PR DESCRIPTION
**Pull request by ivanlori**

### CODE REVIEW

**Comment by ivanlori** [comment]
Ok, I am looking in this failed build

**Comment by ivanlori** [comment]
@svedova is there a detailed log of the build error? In my local I don't see errors and I have also tried running the build and everything seems ok

**Comment by svedova** [comment]
> @svedova is there a detailed log of the build error? In my local I don't see errors and I have also tried running the build and test command and everything seems ok

@ivanlori seems to be a test failing:

```
(node:92) UnhandledPromiseRejectionWarning: TypeError: Caught error after test environment was torn down
Cannot read property 'body' of null
(node:92) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:92) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FAIL src/pages/logout/Logout.spec.js
● pages/Logout › should trigger the logout function on mount
Configuration error:
Could not locate module ~/pages/logout mapped as:
/home/app/repo/src/$1.
Please check your configuration for these entries:
{
"moduleNameMapper": {
"/~(.*)$/": "/home/app/repo/src/$1"
},
"resolver": undefined
}
18 | {
19 | path: "/logout",
> 20 | component: Async(() => import("~/pages/logout"))
| ^
21 | },
22 | {
23 | path: "/apps/new",
at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:553:17)
at src/pages/routes.tsx:20:22
Summary of all failing tests
FAIL src/pages/logout/Logout.spec.js
● pages/Logout › should trigger the logout function on mount
Configuration error:
Could not locate module ~/pages/logout mapped as:
/home/app/repo/src/$1.
Please check your configuration for these entries:
{
"moduleNameMapper": {
"/~(.*)$/": "/home/app/repo/src/$1"
},
"resolver": undefined
}
18 | {
19 | path: "/logout",
> 20 | component: Async(() => import("~/pages/logout"))
| ^
21 | },
22 | {
23 | path: "/apps/new",
at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:553:17)
at src/pages/routes.tsx:20:22
Test Suites: 1 failed, 20 passed, 21 total
Tests: 1 failed, 93 passed, 94 total
Snapshots: 0 total
Time: 43.426 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app.stormkit.io@1.0.0 test: `NODE_ENV=test jest --notify --detectOpenHandles --runInBand --config=config/jest.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app.stormkit.io@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/node/.npm/_logs/2021-01-02T15_00_40_445Z-debug.log
```

**Comment by svedova** [comment]
I think the reason is because of the folder rename: `src/pages/Logout/Logout.tsx`. Previously it was `src/pages/logout/Logout.tsx`. 

Builds are running on a linux environment so folder names are case sensitive.

**Comment by ivanlori** [comment]
Yes, I renamed my local folders to lowercase because I see that project on master has lower cases folder now, is it correct? In that case can I change the path into the Logout.spec.js file?

**Comment by svedova** [comment]
@ivanlori yes please, as per https://github.com/stormkit-io/app-stormkit-io/issues/15 we keep the folder names lowercase and jsx/tsx files capitalised.

**Comment by svedova** [comment]
Be aware that Git is also case insensitive, if you rename the folder name it will be the same for it. I think there is a special process for renaming and committing folders/files. This may help: https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Comment by ivanlori** [comment]
ok, solved @svedova

**Review by svedova — APPROVED** [review]

**Pull request merged**
