### PR TITLE
Typescript infobox migration

### PR DESCRIPTION
**Pull request by ivanlori**
@svedova I would test this component migration on my env, can you tell me where this component is displayed?

### CODE REVIEW

**Comment by svedova** [comment]
Sorry @ivanlori for the late reply, I completely missed this! 

The easiest way is to go to your **Application** > **Settings** and then hit on **Update**. It should display a toaster on top of the page. 

Alternatively, it's also displayed when you create a new application.

**Comment by ivanlori** [comment]
@svedova ok, the PR is ready to be reviewed

**Review by svedova — APPROVED** [review]
LGTM! Thanks 💯

**Comment by svedova** [comment]
Alright, I've rebased and fixed the conflicts. Will merge as soon as the deployment is complete.

**Pull request merged**
